#pragma once
#include "adcs/math.hpp"
#include <Eigen/Cholesky>

namespace adcs {
using Matrix6=Eigen::Matrix<double,6,6>;
struct MekfConfig{double gyro_noise_std=.0003490658503988659,bias_random_walk_std=.00003490658503988659,initial_attitude_std=.2617993877991494,initial_bias_std=.008726646259971648;};
struct MekfState{Quat q_ib{1,0,0,0};Vec3 gyro_bias=Vec3::Zero();Matrix6 covariance=Matrix6::Zero();Vec3 last_innovation=Vec3::Zero();Mat3 last_innovation_covariance=Mat3::Zero();double last_nis=0;};
inline MekfState initialize_mekf(const Quat&q,const Vec3&bias,const MekfConfig&p={}){MekfState x;x.q_ib=normalize(q);x.gyro_bias=bias;x.covariance.diagonal()<<Vec3::Constant(p.initial_attitude_std*p.initial_attitude_std),Vec3::Constant(p.initial_bias_std*p.initial_bias_std);return x;}
inline void mekf_predict(MekfState&x,const Vec3&gyro,double dt,const MekfConfig&p={}){const Vec3 w=gyro-x.gyro_bias;const double angle=w.norm()*dt;Quat dq{1,0,0,0};if(angle!=0)dq<<std::cos(angle/2),std::sin(angle/2)*w/w.norm();x.q_ib=normalize(multiply(x.q_ib,dq));Matrix6 f=Matrix6::Zero();f.topLeftCorner<3,3>()=-skew(w);f.topRightCorner<3,3>()=-Mat3::Identity();const Matrix6 phi=Matrix6::Identity()+f*dt;Matrix6 noise=Matrix6::Zero();noise.diagonal()<<Vec3::Constant(p.gyro_noise_std*p.gyro_noise_std*dt),Vec3::Constant(p.bias_random_walk_std*p.bias_random_walk_std*dt);x.covariance=phi*x.covariance*phi.transpose()+noise;x.covariance=(x.covariance+x.covariance.transpose())/2;}
inline void mekf_update_vector(MekfState&x,const Vec3&measured_body,const Vec3&reference_eci,double noise_std){const Vec3 measured=measured_body.normalized(),predicted=to_dcm(x.q_ib).transpose()*reference_eci.normalized();const Vec3 innovation=measured-predicted;Eigen::Matrix<double,3,6> h=Eigen::Matrix<double,3,6>::Zero();h.leftCols<3>()=skew(predicted);const Mat3 r=noise_std*noise_std*Mat3::Identity();const Mat3 s=h*x.covariance*h.transpose()+r;const Eigen::Matrix<double,6,3> gain=x.covariance*h.transpose()*s.ldlt().solve(Mat3::Identity());const Eigen::Matrix<double,6,1> correction=gain*innovation;Quat dq;dq<<1,correction.head<3>()/2;x.q_ib=normalize(multiply(x.q_ib,normalize(dq)));x.gyro_bias+=correction.tail<3>();const Matrix6 i=Matrix6::Identity(),a=i-gain*h;x.covariance=a*x.covariance*a.transpose()+gain*r*gain.transpose();x.covariance=(x.covariance+x.covariance.transpose())/2;x.last_innovation=innovation;x.last_innovation_covariance=s;x.last_nis=innovation.dot(s.ldlt().solve(innovation));}
inline Quat quest(const Eigen::Ref<const Eigen::Matrix<double,3,Eigen::Dynamic>>&body,const Eigen::Ref<const Eigen::Matrix<double,3,Eigen::Dynamic>>&inertial,const Eigen::Ref<const Eigen::VectorXd>&weights){if(body.cols()!=inertial.cols()||body.cols()!=weights.size())throw std::invalid_argument("QUEST dimensions");Mat3 profile=Mat3::Zero();for(Eigen::Index i=0;i<body.cols();++i)profile+=weights(i)*body.col(i).normalized()*inertial.col(i).normalized().transpose();const double sigma=profile.trace();const Mat3 symmetric=profile+profile.transpose();const Vec3 z{profile(1,2)-profile(2,1),profile(2,0)-profile(0,2),profile(0,1)-profile(1,0)};Eigen::Matrix4d k;k.topLeftCorner<3,3>()=symmetric-sigma*Mat3::Identity();k.topRightCorner<3,1>()=z;k.bottomLeftCorner<1,3>()=z.transpose();k(3,3)=sigma;Eigen::SelfAdjointEigenSolver<Eigen::Matrix4d>s(k);const auto v=s.eigenvectors().col(3);Quat q{v(3),v(0),v(1),v(2)};q=normalize(q);if(q(0)<0)q=-q;return q;}
}  // namespace adcs
